question_bank = [
    {"q": "What is 2 + 2?", "options": ["3", "4", "5"], "answer": "4"},
    {"q": "Which planet do we live on?", "options": ["Mars", "Earth", "Venus"], "answer": "Earth"},
    {"q": "Who wrote 'Romeo and Juliet'?", "options": ["Shakespeare", "Dickens", "Hemingway"], "answer": "Shakespeare"},
    {"q": "What is the capital of France?", "options": ["Paris", "Berlin", "Rome"], "answer": "Paris"},
    {"q": "What is H2O commonly known as?", "options": ["Water", "Oxygen", "Hydrogen"], "answer": "Water"},
    {"q": "Which language is primarily spoken in Spain?", "options": ["English", "Spanish", "French"], "answer": "Spanish"},
    {"q": "How many continents are there?", "options": ["5", "6", "7"], "answer": "7"},
    {"q": "Which organ pumps blood?", "options": ["Lungs", "Liver", "Heart"], "answer": "Heart"},
    {"q": "What is the boiling point of water?", "options": ["100°C", "50°C", "80°C"], "answer": "100°C"},
    {"q": "Which gas do plants absorb?", "options": ["Oxygen", "Nitrogen", "Carbon Dioxide"], "answer": "Carbon Dioxide"},
    
    {"q": "What color do you get by mixing red and white?", "options": ["Pink", "Purple", "Orange"], "answer": "Pink"},
    {"q": "Which animal is known as the King of the Jungle?", "options": ["Lion", "Tiger", "Elephant"], "answer": "Lion"},
    {"q": "What is the freezing point of water?", "options": ["0°C", "100°C", "-10°C"], "answer": "0°C"},
    {"q": "Who painted the Mona Lisa?", "options": ["Van Gogh", "Da Vinci", "Picasso"], "answer": "Da Vinci"},
    {"q": "What is the largest planet in our Solar System?", "options": ["Earth", "Saturn", "Jupiter"], "answer": "Jupiter"},
    {"q": "Which element has the chemical symbol 'O'?", "options": ["Gold", "Oxygen", "Silver"], "answer": "Oxygen"},
    {"q": "How many states are there in the USA?", "options": ["50", "52", "48"], "answer": "50"},
    {"q": "What is the speed of light?", "options": ["300,000 km/s", "150,000 km/s", "1,000 km/s"], "answer": "300,000 km/s"},
    {"q": "Which ocean is the largest?", "options": ["Atlantic", "Pacific", "Indian"], "answer": "Pacific"},
    {"q": "Who invented the telephone?", "options": ["Tesla", "Edison", "Bell"], "answer": "Bell"},
    
    {"q": "What is the chemical formula for salt?", "options": ["NaCl", "H2O", "CO2"], "answer": "NaCl"},
    {"q": "Which country is known as the Land of the Rising Sun?", "options": ["China", "Japan", "Korea"], "answer": "Japan"},
    {"q": "What does DNA stand for?", "options": ["Deoxyribonucleic Acid", "Dinucleic Acid", "Dioxyribose Acid"], "answer": "Deoxyribonucleic Acid"},
    {"q": "Which planet is known as the Red Planet?", "options": ["Venus", "Mars", "Jupiter"], "answer": "Mars"},
    {"q": "How many legs does a spider have?", "options": ["6", "8", "10"], "answer": "8"},
    {"q": "What is the hardest natural substance on Earth?", "options": ["Gold", "Diamond", "Iron"], "answer": "Diamond"},
    {"q": "Who developed the theory of relativity?", "options": ["Newton", "Einstein", "Tesla"], "answer": "Einstein"},
    {"q": "What gas do humans breathe in?", "options": ["Oxygen", "Carbon Dioxide", "Nitrogen"], "answer": "Oxygen"},
    {"q": "Which country hosted the 2016 Summer Olympics?", "options": ["China", "Brazil", "UK"], "answer": "Brazil"},
    {"q": "What is the main ingredient in bread?", "options": ["Rice", "Wheat", "Corn"], "answer": "Wheat"},
    
    {"q": "Which is the largest mammal?", "options": ["Elephant", "Blue Whale", "Giraffe"], "answer": "Blue Whale"},
    {"q": "How many bones are in the human body?", "options": ["206", "210", "201"], "answer": "206"},
    {"q": "Which continent is the Sahara Desert located on?", "options": ["Asia", "Africa", "Australia"], "answer": "Africa"},
    {"q": "What do bees collect from flowers?", "options": ["Honey", "Pollen", "Nectar"], "answer": "Nectar"},
    {"q": "What is the currency of Japan?", "options": ["Yuan", "Yen", "Won"], "answer": "Yen"},
    {"q": "Who is the author of 'Harry Potter'?", "options": ["J.K. Rowling", "Tolkien", "C.S. Lewis"], "answer": "J.K. Rowling"},
    {"q": "What is the tallest mountain in the world?", "options": ["K2", "Everest", "Kangchenjunga"], "answer": "Everest"},
    {"q": "Which planet has rings?", "options": ["Saturn", "Mars", "Jupiter"], "answer": "Saturn"},
    {"q": "Which is the smallest prime number?", "options": ["1", "2", "3"], "answer": "2"},
    {"q": "What does the CPU in a computer stand for?", "options": ["Central Processing Unit", "Computer Personal Unit", "Central Program Unit"], "answer": "Central Processing Unit"},
    
    {"q": "Who painted the ceiling of the Sistine Chapel?", "options": ["Michelangelo", "Raphael", "Da Vinci"], "answer": "Michelangelo"},
    {"q": "Which gas is most abundant in the Earth's atmosphere?", "options": ["Oxygen", "Nitrogen", "Carbon Dioxide"], "answer": "Nitrogen"},
    {"q": "What is the chemical symbol for gold?", "options": ["Ag", "Au", "Gd"], "answer": "Au"},
    {"q": "How many teeth does an adult human have?", "options": ["28", "32", "30"], "answer": "32"},
    {"q": "Which country has the Great Barrier Reef?", "options": ["Australia", "USA", "South Africa"], "answer": "Australia"},
    {"q": "Who is known as the Father of Computers?", "options": ["Charles Babbage", "Alan Turing", "Bill Gates"], "answer": "Charles Babbage"},
    {"q": "Which planet is the hottest in the solar system?", "options": ["Venus", "Mercury", "Mars"], "answer": "Venus"},
    {"q": "What is the largest organ in the human body?", "options": ["Liver", "Skin", "Heart"], "answer": "Skin"},
    {"q": "Who discovered penicillin?", "options": ["Marie Curie", "Alexander Fleming", "Louis Pasteur"], "answer": "Alexander Fleming"},
    {"q": "What is the study of plants called?", "options": ["Zoology", "Botany", "Ecology"], "answer": "Botany"},
    
    {"q": "What is the longest river in the world?", "options": ["Amazon", "Nile", "Yangtze"], "answer": "Nile"},
    {"q": "Which is the smallest country in the world?", "options": ["Monaco", "Vatican City", "Malta"], "answer": "Vatican City"},
    {"q": "What device do we use to look at stars?", "options": ["Microscope", "Telescope", "Periscope"], "answer": "Telescope"},
    {"q": "What is the capital city of Australia?", "options": ["Sydney", "Melbourne", "Canberra"], "answer": "Canberra"},
    {"q": "How many players are there in a soccer team?", "options": ["9", "10", "11"], "answer": "11"},
    {"q": "Which organ is responsible for breathing?", "options": ["Heart", "Lungs", "Kidneys"], "answer": "Lungs"},
    {"q": "Which metal is liquid at room temperature?", "options": ["Mercury", "Gold", "Copper"], "answer": "Mercury"},
    {"q": "What is the main gas found in balloons?", "options": ["Helium", "Hydrogen", "Oxygen"], "answer": "Helium"},
    
    {"q": "What is the name of the galaxy we live in?", "options": ["Andromeda", "Milky Way", "Whirlpool"], "answer": "Milky Way"},
    {"q": "Which planet has the shortest day?", "options": ["Jupiter", "Mars", "Earth"], "answer": "Jupiter"},
    {"q": "What is the chemical symbol for silver?", "options": ["Ag", "Au", "Si"], "answer": "Ag"},
    {"q": "Which animal is known for its black and white stripes?", "options": ["Tiger", "Zebra", "Leopard"], "answer": "Zebra"},
    {"q": "What vitamin do we get from sunlight?", "options": ["Vitamin A", "Vitamin C", "Vitamin D"], "answer": "Vitamin D"},
    {"q": "What is the process by which plants make food?", "options": ["Respiration", "Photosynthesis", "Transpiration"], "answer": "Photosynthesis"},
    {"q": "Who is the author of 'The Hobbit'?", "options": ["J.K. Rowling", "Tolkien", "C.S. Lewis"], "answer": "Tolkien"},
    {"q": "What is the chemical formula for carbon dioxide?", "options": ["CO", "CO2", "C2O"], "answer": "CO2"},
    {"q": "Which planet is known for its beautiful rings?", "options": ["Saturn", "Uranus", "Neptune"], "answer": "Saturn"},
    {"q": "How many colors are there in a rainbow?", "options": ["6", "7", "8"], "answer": "7"},
    
    {"q": "What is the smallest unit of life?", "options": ["Atom", "Cell", "Molecule"], "answer": "Cell"},
    {"q": "Which blood type is known as the universal donor?", "options": ["A", "O", "AB"], "answer": "O"},
    {"q": "What gas do animals exhale?", "options": ["Oxygen", "Carbon Dioxide", "Nitrogen"], "answer": "Carbon Dioxide"},
    {"q": "Which is the fastest land animal?", "options": ["Cheetah", "Lion", "Tiger"], "answer": "Cheetah"},
    {"q": "What is the main source of energy for the Earth?", "options": ["Moon", "Sun", "Stars"], "answer": "Sun"},
    {"q": "What type of instrument measures temperature?", "options": ["Barometer", "Thermometer", "Hygrometer"], "answer": "Thermometer"},
    {"q": "Who discovered gravity?", "options": ["Newton", "Einstein", "Galileo"], "answer": "Newton"},
    {"q": "What is the hardest rock?", "options": ["Granite", "Diamond", "Marble"], "answer": "Diamond"},
    {"q": "Which part of the plant absorbs water?", "options": ["Leaves", "Roots", "Stem"], "answer": "Roots"},
    {"q": "What is the chemical symbol for iron?", "options": ["Fe", "Ir", "In"], "answer": "Fe"},
    
    {"q": "What does 'WWW' stand for?", "options": ["World Wide Web", "World Web Wide", "Web World Wide"], "answer": "World Wide Web"},
    {"q": "What is the main language spoken in Brazil?", "options": ["Spanish", "Portuguese", "French"], "answer": "Portuguese"},
    {"q": "Which planet is closest to the Sun?", "options": ["Mercury", "Venus", "Earth"], "answer": "Mercury"},
    {"q": "What is the name of the longest bone in the human body?", "options": ["Femur", "Tibia", "Humerus"], "answer": "Femur"},
    {"q": "What is the boiling point of water at sea level in Fahrenheit?", "options": ["212°F", "100°F", "180°F"], "answer": "212°F"},
    {"q": "Which continent is the largest by area?", "options": ["Asia", "Africa", "Europe"], "answer": "Asia"},
    {"q": "What is the powerhouse of the cell?", "options": ["Nucleus", "Mitochondria", "Ribosome"], "answer": "Mitochondria"},
    {"q": "Who is the first person to walk on the Moon?", "options": ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin"], "answer": "Neil Armstrong"},
    {"q": "What is the freezing point of water in Fahrenheit?", "options": ["32°F", "0°F", "100°F"], "answer": "32°F"},
    {"q": "What does 'HTTP' stand for?", "options": ["HyperText Transfer Protocol", "Hyperlink Text Transfer Protocol", "HyperText Transmission Protocol"], "answer": "HyperText Transfer Protocol"},
]